# Generated by Django 2.1.15 on 2021-03-29 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='users',
            new_name='user',
        ),
    ]
